name = "estacao-meteorologica-constelacion"
main = "src/index.js"
compatibility_date = "2026-08-30"

[[d1_databases]]
binding = "DB"
database_name = "estacao-meteorologica-db"
database_id = "a6ce745d-8edc-4770-9ac7-5e5f9df75fc2"

[assets]
directory = "."
